### ISSUE TITLE
User Login Core Components.

### ISSUE THREAD

**Issue by lpsandaruwan** [lpsandaruwan/depli#9]
- [ ] Required entities, repositories and services implementation.
- [ ] Controller implementaion with JWT token authentication.
- [ ] Spring application configurations.

**Comment by alefhsousa** [comment]
Hi @lpsandaruwan this feature can be implemented with spring security ?

**Comment by lpsandaruwan** [comment]
Yes. That is depli's expectation. :-)

**Comment by lpsandaruwan** [comment]
Fixed with https://github.com/lpsandaruwan/depli/pull/19
